automagic_project/automagic/automated/urls.py
# -*- coding:utf-8 -*-
"""automated URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login,logout
# from django.conf import settings
from autoplat import views as automate
from webinterface import views as interface
# from deviceapp import views as devicemgt

from rest_framework import routers

# Routers provide an easy way of automatically determining the URL conf.

router = routers.DefaultRouter()
router.register(r'product', automate.ProductViewSet)
router.register(r'project', automate.ProjectViewSet)
router.register(r'module', automate.ModuleViewSet)
router.register(r'keyword', automate.KeywordViewSet)
router.register(r'element', automate.ElementViewSet)
router.register(r'case', automate.CaseViewSet)
router.register(r'step', automate.StepViewSet)


admin.autodiscover()
urlpatterns = [
    url(r'^test/$', automate.comingsoon, name='test'),
    url(r'^login', login),
    url(r'^logout', logout, {'next_page': '/login/'}),
    url(r'^func/case/add/$', automate.add_case, name='caseadd'),
    url(r'^func/case/list/$|^$|^index/$', login_required(automate.CaseListIndex.as_view()), name='caselist'),
    url(r'^func/case/view/(?P<id>\d+)/$', automate.view_case, name='caseview'),
    url(r'^func/case/update/(?P<id>\d+)/$', automate.update_case, name='caseupdate'),
    url(r'^func/case/copy/(?P<id>\d+)/$', automate.copy_case, name='copycase'),
    url(r'^func/case/del/(?P<id>\d+)/$', automate.del_case, name='casedel'),
    url(r'^func/case/run/$', automate.run_case, name='runcase'),
    url(r'^func/get/caselist/$', automate.get_caselist, name='getcase'),
    url(r'^func/step/del/(?P<id>\d+)/$', automate.del_step, name='stepdel'),
    url(r'^func/element/list/$', login_required(automate.ElementListIndex.as_view()), name='elementlist'),
    url(r'^func/element/add/$', automate.add_element, name='elementadd'),
    url(r'^func/element/update/$', automate.update_element, name='elementupdate'),
    url(r'^func/element/del/(?P<id>\d+)/$', automate.del_element, name='elementdel'),
    url(r'^func/keyword/list/$', login_required(automate.KeyWordListIndex.as_view()), name='keywordlist'),
    url(r'^func/keyword/add/$', automate.add_keyword, name='keywordadd'),
    url(r'^func/keyword/update/$', automate.update_keyword, name='keywordupdate'),
    url(r'^func/keyword/del/(?P<id>\d+)/$', automate.del_keyword, name='keyworddel'),
    url(r'^func/get/keyword/$', automate.get_keyword, name='getkeyword'),
    url(r'^func/get/element/$', automate.get_element, name='getelement'),
    url(r'^func/setedit/element/$', automate.set_edit_element, name='seteditelement'),
    url(r'^func/setedit/keyword/$', automate.set_edit_keyword, name='seteditelement'),
    url(r'^func/task/add/$', automate.add_task, name='taskadd'),
    url(r'^func/task/list/$', login_required(automate.TaskListIndex.as_view()), name='tasklist'),
    url(r'^func/setTree/task/$', automate.set_tree_task, name='settreetask'),
    url(r'^func/task/update/(?P<id>\d+)/$', automate.update_task, name='taskupdate'),
    url(r'^func/task/del/(?P<id>\d+)/$', automate.del_task, name='taskdel'),
    url(r'^func/task/run/$', automate.run_task, name='runtask'),
    url(r'^func/get/taskhistory/$', automate.get_task_history, name='gettaskhistroy'),
    url(r'^setting/user/add/$', automate.add_user, name='adduser'),
    url(r'^setting/user/list/$', login_required(automate.UserListIndex.as_view()), name='userlist'),
    url(r'^setting/user/update/$', automate.update_user, name='userupdate'),
    url(r'^setting/user/del/(?P<id>\d+)/$', automate.del_user, name='userdel'),
    url(r'^setting/product/add/$', automate.add_product, name='productadd'),
    url(r'^setting/product/view/(?P<id>\d+)', automate.view_product, name='productview'),
    url(r'^setting/product/list/$', login_required(automate.ProductListIndex.as_view()), name='productlist'),
    url(r'^setting/product/update/$', automate.update_product, name='productupdate'),
    url(r'^setting/product/del/(?P<id>\d+)/$', automate.del_product, name='productdel'),
    url(r'^setting/project/add/$', automate.add_project, name='projectadd'),
    url(r'^setting/project/list/$', login_required(automate.ProjectListIndex.as_view()), name='projectlist'),
    url(r'^setting/project/view/(?P<id>\d+)', automate.view_project, name='projectview'),
    url(r'^setting/project/update/$', automate.update_project, name='projectupdate'),
    url(r'^setting/project/del/(?P<id>\d+)/$', automate.del_project, name='projectdel'),
    url(r'^setting/module/add/$', automate.add_module, name='moduleadd'),
    url(r'^setting/module/list/$', login_required(automate.ModuleListIndex.as_view()), name='modulelist'),
    url(r'^setting/module/update/$', automate.update_module, name='moduleupdate'),
    url(r'^setting/module/del/(?P<id>\d+)/$', automate.del_module, name='moduledel'),
    url(r'^setting/get/project/$', automate.get_project, name='getproject'),
    url(r'^setting/get/module/$', automate.get_module, name='getmodule'),
    url(r'^setting/get/connecteduser/$', automate.get_connected_user, name='getconnecteduser'),
    url(r'^setting/product/user/$', automate.product_user, name='productuser'),
    url(r'^setting/get/moduleList/$', automate.get_module_list, name='getmodulelist'),
    url(r'^setting/setedit/product/$', automate.set_edit_product, name='seteditproduct'),
    url(r'^setting/setedit/project/$', automate.set_edit_project, name='seteditproject'),
    url(r'^setting/setedit/module/$', automate.set_edit_module, name='seteditmodule'),
    url(r'^setting/setedit/user/$', automate.set_edit_user, name='setedituser'),
    url(r'^interf/web/home/$',  login_required(interface.WebinterfaceListIndex.as_view()), name='webinterface'),
    url(r'^interf/get/response/$', interface.get_response, name='getresponse'),
    url(r'^tools/syslog/home/$', automate.page_syslog, name='toolsyslog'),
    url(r'^tools/snmp/home/$', automate.comingsoon, name='toolsnmp'),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^user/login', devicemgt.user_login),
    # url(r'^device/usedList', devicemgt.device_used_detail_info),
    # url(r'^device/list', devicemgt.device_table_info, name='device_detail'),
    # url(r'^device/borrow', devicemgt.bowrrow_device, name='borrow_device'),
    # url(r'^device/sendBack', devicemgt.sendback_device, name='device_sendBack'),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

automagic_project/automagic/autoplat/models.py
# -*- coding:utf-8 -*-
"""
__author__ = 'Ray'
mail:tsbc@vip.qq.com
2016-08-03
"""
from __future__ import unicode_literals

import datetime

from django.core.validators import validate_comma_separated_integer_list
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=32, verbose_name='产品名称', unique=True)
    # version = models.CharField(max_length=32)
    isenabled = models.BooleanField(default=True, blank=True, verbose_name='产品状态')
    descr = models.TextField(null=True, blank=True, verbose_name='产品描述')
    createtime = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name='创建时间')
    createat = models.CharField(max_length=32, null=True, blank=True, editable=True, verbose_name='创建者')
    updatetime = models.DateTimeField(auto_now=True,null=True, blank=True, verbose_name='更新时间')
    updateat = models.CharField(max_length=32, null=True, blank=True, editable=True, verbose_name='更新者')
    sortby = models.IntegerField(null=True, blank=True, editable=True, default=0, verbose_name='排序')

    def __unicode__(self):
        return  self.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.createtime = datetime.datetime.now()
            self.updatetime = datetime.datetime.now()

        super(Product, self).save(*args, **kwargs)

    class Meta:
        ordering = ["-sortby"]

class Project(models.Model):
    productid = models.ForeignKey(Product, verbose_name='产品名称')
    name = models.CharField(max_length=32, unique=True, verbose_name='项目名称')
    version = models.CharField(max_length=32, null=True, blank=True, editable=True, verbose_name='版本')
    isenabled = models.BooleanField(default=True, verbose_name='状态')
    descr = models.TextField(null=True, blank=True, editable=True,verbose_name='项目描述')
    createtime = models.DateTimeField(auto_now_add=True, null=True, blank=True, editable=True,verbose_name='创建时间')
    createat = models.CharField( max_length=32, null=True, blank=True, editable=True, verbose_name='创建者')
    updatetime = models.DateTimeField(auto_now=True,null=True, blank=True, verbose_name='更新时间')
    updateat = models.CharField(max_length=32, null=True, blank=True, editable=True, verbose_name='更新者')
    sortby = models.IntegerField(null=True, blank=True, editable=True, default=0, verbose_name='排序')

    def __unicode__(self):
        return  self.name

    class Meta:
        ordering = ["-sortby"]

class Module(models.Model):
    projectid = models.ForeignKey(Project, verbose_name='所属项目')
    name = models.CharField(max_length=32, verbose_name='模块名称')
    isenabled = models.BooleanField(default=True, verbose_name='状态')
    createtime = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    createat = models.CharField(max_length=32 ,null=True, blank=True, editable=True, verbose_name='创建者')
    updatetime = models.DateTimeField(auto_now=True, verbose_name='更新时间')
    updateat = models.CharField(max_length=32, null=True, blank=True, editable=True, verbose_name='更新者')
    sortby = models.IntegerField(null=True, blank=True, editable=True, default=0, verbose_name='排序')

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ["-sortby"]

class Keyword(models.Model):
    productid = models.IntegerField(verbose_name='所属产品', null=True, blank=True, editable=True)
    keyword = models.CharField(max_length=32, unique=True)
    kwdescr = models.TextField(null=True,blank=True,editable=True)
    createtime = models.DateTimeField(auto_now_add=True)
    createat = models.CharField(max_length=32, null=True, blank=True, editable=True)
    updatetime = models.DateTimeField(auto_now=True)
    updateat = models.CharField(max_length=32, null=True, blank=True, editable=True)

    def __unicode__(self):
        return self.keyword

    class Meta:
        ordering = ["productid"]

class Element(models.Model):
    Element_Choice = (
        ('id','id'),
        ('name','name'),
        ('css selector','css selector'),
        ('xpath','xpath'),
        ('class_name','class name'),
        ('tag_name','tag name'),
        ('link_text','link text'),
        ('portial_link_text','portial link text')
    )
    projectid = models.ForeignKey(Project,editable=True)
    moduleid = models.ForeignKey(Module, editable=True)
    descr = models.CharField(max_length=100, editable=True)
    locmode = models.CharField(max_length=32, choices=Element_Choice, null=True, blank=True, editable=True)
    location = models.CharField(max_length=200, null=True, blank=True, editable=True)
    createtime = models.DateTimeField(auto_now_add=True)
    createat = models.CharField(max_length=32, null=True, blank=True, editable=True)
    updatetime = models.DateTimeField(auto_now=True)
    updateat = models.CharField(max_length=32, null=True, blank=True, editable=True)

    def __unicode__(self):
        return self.descr

class Case(models.Model):
    projectid = models.ForeignKey(Project)
    moduleid = models.ForeignKey(Module)
    testrailcaseid = models.CharField(max_length=12,null=True, blank=True, editable=True)
    casedesc = models.CharField(max_length=255, verbose_name="Title")
    isenabled = models.BooleanField(default=True)
    issmoke = models.BooleanField(default=False)
    dependent = models.CharField(max_length=8,null=True, blank=True, editable=True)
    debuginfo = models.CharField(max_length=9999, null=True, blank=True, editable=True)
    createtime = models.DateTimeField(auto_now_add=True)
    createat = models.CharField(max_length=32,null=True, blank=True, editable=True)
    updatetime = models.DateTimeField(auto_now_add=True)
    updateat = models.CharField(max_length=32,null=True, blank=True, editable=True)

    def __unicode__(self):
        return self.casedesc

class Caseset(models.Model):
    descr = models.CharField(max_length=200)
    caseid = models.CharField(validators=[validate_comma_separated_integer_list],max_length=255)
    isenabled = models.BooleanField(default=True)
    createtime = models.DateTimeField(auto_now_add=True)
    createat = models.CharField(max_length=32, null=True, blank=True, editable=True)
    updatetime = models.DateTimeField(auto_now=True)
    updateat = models.CharField(max_length=32, null=True, blank=True, editable=True)

    def __unicode__(self):
        return self.descr

class Step(models.Model):
    caseid = models.ForeignKey(Case)
    stepid = models.IntegerField(null=True, blank=True, editable=True)
    descr = models.CharField(max_length=200, null=True, blank=True, editable=True)
    keywordid = models.ForeignKey(Keyword)
    elementid = models.ForeignKey(Element,null=True, blank=True)
    inputtext = models.CharField(max_length=200, null=True, blank=True, editable=True)
    createtime = models.DateTimeField(auto_now_add=True)
    createat = models.CharField(max_length=32, null=True, blank=True, editable=True)
    updatetime = models.DateTimeField(auto_now=True)
    updateat = models.CharField(max_length=32, null=True, blank=True, editable=True)

    def __unicode__(self):
        return  self.descr

class MyUserManager(BaseUserManager):
    # def current_time(self):
    #     """get current time """
    #     from datetime import datetime
    #     return datetime.now().strftime("%Y-%m-%d")

    def create_user(self, username, email, password):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """

        if not username:
            raise ValueError('username is unique')
        user = self.model(username=username, email=self.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password):
        """
        Creates and saves a superuser with the given email, password.
        """
        user = self.create_user(username, email, password)
        user.is_admin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    Dept_Choice = (
        ('测试', '测试'),
        ('开发', '开发'),
    )
    username = models.CharField(max_length=50, verbose_name="username", unique=True, null=True)
    password = models.CharField(('password'), max_length=128)
    realname = models.CharField(max_length=50, verbose_name="真实姓名", null=True, blank=True, editable=True)
    mobile = models.CharField(max_length=11, verbose_name="Phone Number", null=True, blank=True, editable=True)
    email = models.EmailField(verbose_name='Email Address', max_length=255, unique=True)
    dept = models.CharField(verbose_name=u'部门',choices=Dept_Choice, max_length=100)
    is_active = models.BooleanField(default=True, verbose_name='激活状态')
    is_admin = models.BooleanField(default=False, verbose_name='是否管理员')
    testrailuser = models.CharField(max_length=50, verbose_name="TestRail用户名", null=True,blank=True, editable=True)
    testrailpass = models.CharField(max_length=50, verbose_name="TestRail密码", null=True,blank=True, editable=True)
    objects = MyUserManager()
    base_objects = BaseUserManager()
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def get_full_name(self):
        # The user is identified by their email address
        return self.username

    def get_short_name(self):
        # The user is identified by their email address
        return self.username

    def __unicode__(self):  # __unicode__ on Python 2
        return self.username

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"

automagic_project/automagic/autoplat/templates/caseadd.html
{% extends 'frame.html' %}
{% block title %}Automagic{% endblock %}
{% block slideshow %}
    <div class="ak-zper-midbox ak-jsch-mid">
         <div class="ak-zper-inbox-title ak-jsch-title clearfix">
               <div class="ak-left ak-jsch-row3 ak-zper-fix-btnbox">
                    <span class="ak-zper-remindback"></span>
                    <span class="inbox-text">添加用例</span>
               </div>
             <div id="log_info" class="ac-addtips"></div>
            <select id="selproductid" name="caseproductname" class="ak-right ak-left ac-aselect ac-margint8">
                      <option value="0">-产品名称-</option>
                          {% for product in userandproduct  %}
                              {% if product.username == request.user %}
                                  <option value="{{ product.productname.id }}" {% if request.GET.productname  == product.productname %}selected{% endif %}>{{ product.productname }}</option>
                              {% endif %}
                          {% endfor %}
                </select>

          </div>

      	  <div class="col-md-12">
 <form method='post'  id="case_add">
    {% csrf_token %}
    <div class="ak-jsch-modal-row col01">
        <div class="ak-jsch-pos">
            <div class="ak-jsch-point">
            </div>
        </div>
        <div class="ak-jsch-modal-text col01 clearfix">
            <span class="ak-jsch-item-left ak-left ">用例描述</span>
            <div class="ak-jsch-item-right col02 ak-left">
                <input id="casedesc" name="casedesc" class="ak-jsch-modal-input" type="text" required="" placeholder="测试用例描述">
            </div>
        </div>
    </div>
     <div class="ak-jsch-modal-row col01 ak-jsch-padding">
         <div class="ak-jsch-modal-text">
             <div class="ak-jsch-modal-item clearfix"><span class="ak-left ak-jsch-item-left ">状态</span>
                 <div class="sky-form col01 ak-left ac-ml10">
                     <label class="toggle">
                         <input type="checkbox" id="id_isenabled" name="isenabled" checked="checked">
                         <i class="rounded-4x ak-aoffon-btn"></i>
                     </label>
                 </div>
             </div>
             <div class="ak-jsch-modal-item ak-jsch-pt clearfix">
                 <span class="ak-jsch-item-left ak-left">项目</span>
                 <div class="ak-jsch-item-right ak-left">
                     <select id="selprojectid" name="projectid" class="ak-left ac-aselect col01" required=""></select>
                 </div>
             </div>
             <div class="ak-jsch-modal-item ak-jsch-pt clearfix">
                 <span class="ak-jsch-item-left ak-left">模块</span>
                 <div class="ak-jsch-item-right ak-left">
                     <select id="selmoduleid" name="moduleid" class="ak-left ac-aselect col01" required=""><option value="">所属模块</option></select>
                 </div>
             </div>
             <div class="ak-jsch-modal-item clearfix"><span class="ak-left ak-jsch-item-left ">冒烟测试</span>
                 <div class="sky-form col01 ak-left ac-ml10">
                     <label class="toggle">
                         <input type="checkbox" id="id_issmoke" name="issmoke">
                         <i class="rounded-4x ak-aoffon-btn"></i>
                     </label>
                 </div>
             </div>
             <div class="ak-jsch-modal-item ak-jsch-pt clearfix">
                 <span class="ak-jsch-item-left ak-left">依赖用例</span>
                 <div class="ak-jsch-item-right ak-left">
                     <input id="id_dependent" name="dependent" type="text" placeholder="请输入依赖用例的编号" class="ac-acaseedit-input" />
                 </div>
             </div>
            <div class="ak-jsch-modal-item ak-jsch-pt clearfix">
                 <span class="ak-jsch-item-left ak-left ac-acase-desc">TestRail ID</span>
                 <div class="ak-jsch-item-right ak-left">
                     <input id="id_testrailcaseid" name="testrailcaseid" type="text" placeholder="关联TestRail的用例编号" class="ac-acaseedit-input" />
                 </div>
             </div>
             <table class="table table-conde" id="tab" style="width:100%">
                 <caption class="text-left">
                    <button type="button" onclick="case_step_addtr();" class="text-left ac-btn-addcase orange ac-margin-tb15">添加一行</button>
                     <input class="ac-acaseedit-input" id="rowid" value="" type="number" placeholder="添加到第N行之后">
                 </caption>
                 <thead>
                 <th>Step No</th>
                 <th>Step Descr</th>
                 <th>Keyword</th>
                 <th>Element</th>
                 <th>Input</th>
                 <th>操作</th>
                 <input hidden="true" id="linecounter"   value = 1 type='text' >
                 </thead>
                 <tbody>
                 <tr id="row1">
                     <td>1</td>
                     <td><input name="descr" class="ac-acaseedit-input" placeholder="请输入步骤描述" type="input" required=""></td>
                     <td><select id="keyword_1" name="keyword" class="ak-left ac-aselect col01" required=""></select></td>
                     <td>
{#                         <select id="id_elementid" name="elementid" class="ak-left ac-aselect col01"><option value="None">请选择可用元素</option></select>#}
                         <input id="autocomplete_1" name="autocomplete" class="ui-autocomplete-input ac-element-input" type="input"><input type="hidden" id="elementid_1" name="elementid" value="None">
                     </td>
                     <td><input name="inputtext" class="ac-keywordtext-input" placeholder="" type="input" ></td>
                     <td></td>
                 </tr>
                 </tbody>
                 <tfoot class="text-left">

                 </tfoot>
             </table>
             <button type="button" onclick="case_step_addtr();" class="text-left ac-btn-addcase orange ac-margin-tb15">添加一行</button>
             <div style="text-align: center;">
                <input  class="btn btn-sm btn-primary" type="submit" value="提交">
                <input class="btn btn-sm btn-default" type="reset" value="重置">
                 <button onclick="goback();" class="btn btn-sm btn-success" role="button">取消>></button>
             </div>
            <div></div>
         </div>
     </div>
     <div><br><br></div>
 </form>
          </div>
    </div>
{% endblock %}
{% block script %}
{% load staticfiles %}
<script type="text/javascript" src="{% static 'js/casemanage.js' %}"></script>
{% endblock %}

automagic_project/automagic/autoplat/templates/index2.html
{% extends 'nav.html' %}
{% block title %}Hello Automated{% endblock %}
{% block slideshow %}
        <br/><br/><br/>

    <a href="/product/list/" class="btn btn-primary">product list</a>
    <a href="/project/list/" class="btn btn-primary">project list</a>
    <a href="/case/list/" class="btn btn-primary">Case list</a>
    <a href="/element/list/" class="btn btn-primary">Element list</a>
    <a href="/keyword/list/" class="btn btn-primary">Keyword list</a>
{% endblock %}

automagic_project/automagic/autoplat/templates/productadd.html
{% extends 'nav.html' %}
{% block title %}Product Add{% endblock %}

{% block slideshow %}
    <br/><br/><br/>
<form method='post'>
    {% csrf_token %}
    <table>
        {{ productform.as_table }}
    </table>
    <input class="btn btn-primary" type="submit" value="submit">
    <input class="btn btn-primary" type="reset" value="reset">
</form>
{% endblock %}

automagic_project/automagic/autoplat/templates/projectadd.html
{% extends 'nav.html' %}
{% block title %}Project Add{% endblock %}

{% block slideshow %}
    <br/><br/><br/>
<form method='post'>
    {% csrf_token %}
    <table>
        {{ projectform.as_table }}
    </table>
    <input class="btn btn-primary" type="submit" value="submit">
    <input class="btn btn-primary" type="reset" value="reset">
</form>
</body>
{% endblock %}

automagic_project/automagic/autoplat/templates/projectlist.html
{% extends 'nav.html' %}
{% block title %}Project List{% endblock %}
{% block slideshow %}
    <br/><br/><br/>
    <form class="form-inline" role="form" action="" method="GET">
        <div class="panel panel-default">
    <div class="panel-heading">
          <div class="form-group">
            <select id="selproductid" name="productid" class="form-control">
              <option value="">-所属产品-</option>
              {% for i in productlist %}
                 <option value="{{ i.pk }}" {% if request.GET.productname  == i.pk %}selected{% endif %}>{{ i.name }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-group">
            <select id="id_projectid" name="projectid" class="form-control">
              <option value="">-所属项目-</option>
            </select>
          </div>
          <div class="form-group">
            <div class="input-group">
                <input type="input" class="form-control" name="keyword" value="{{ request.GET.keyword }}"  placeholder="Search for Keyword">
                  <span class="input-group-btn">
                      <button class="btn btn-primary" type="submit">Go!</button>
                  </span>
              </div><!-- /input-group -->
          </div>
{#          <button type="submit" class="btn btn-primary">Search</button>#}
      </div>
        <table class="table table-striped table-bordered table-hover table-condensed">
        <thead>
          <tr>
              <th>NO.</th>
              <th>产品名称</th>
              <th>项目名称</th>
              <th>版本</th>
              <th>状态</th>
              <th>项目描述</th>
              <th>排序</th>
              <th>创建者</th>
              <th>创建时间</th>
              <th>更新者</th>
              <th>更新时间</th>
          <th></th>
          </tr>
        </thead>
        <tbody>
          {% for project in projectlist %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ project.productid }}</td>
                <td class="ac-alist-descp"><a href="{% url 'projectview' project.id %}"/> {{ project.name }}</td>
                <td>{{ project.version }}</td>
                <td>
                    {% if project.isenabled == True %}
                        <span ng-if="f.flag==true" class="label label-success ng-scope">启 用</span>
                    {% else %}
                        <span ng-if="f.flag==false" class="label label-danger ng-scope">停 用</span>
                    {% endif %}
                </td>
                <td>{{ project.descr }}</td>
                <td>{{ project.sortby }}</td>
                <td>{{ project.createat }}</td>
                <td>{{ project.createtime|date:'Y-m-d H:i:s' }}</td>
                <td>{{ project.createat }}</td>
                <td>{{ project.updatetime|date:'Y-m-d H:i:s' }}</td>
                <th>
                    <a href="{% url 'projectupdate' project.id %}" class="btn btn-sm btn-primary" role="button">编辑</a>
                    <a href="{% url 'projectdel' project.id %}" class="btn btn-sm btn-danger" role="button" onclick="return confirm('Are you Sure Deleted.')">删除</a>
                </th>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
        {% if is_paginated %}
        <div class="panel-default">
        <ul class="pagination">
          <li><a href="{{ request.path }}?page=1">«</a></li>
          {% if page_obj.has_previous %}
            <li><a href="{{ request.path }}?&page={{ page_obj.previous_page_number }}">上一页</a></li>
          {% else %}
            <li class="previous disabled"><a>上一页</a></li>
          {% endif %}
          {% for i in page_obj.paginator.page_range %}
            <li {% if page_obj.number == i %}class="active"{% endif %}><a href="{{ request.path }}?page={{ i }}">{{ i }}</a></li>
          {% endfor %}
          {% if page_obj.has_next %}
            <li><a href="{{ request.path }}?page={{ page_obj.next_page_number }}">下一页</a></li>
          {% else %}
            <li class="previous disabled"><a>下一页</a></li>
          {% endif %}
          <li><a href="{{ request.path }}?page={{ page_obj.paginator.num_pages }}">»</a></li>
            <li><a>当前第{{ page_obj.number }}页/共{{ projectsum }}条</a></li>
        </ul>
    </div>
        {% endif %}
  </form>
{% endblock %}